# Generated by Django 4.2.11 on 2024-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshoApp', '0002_payment_babe_c_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
