# Generated by Django 4.2.11 on 2024-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshoApp', '0003_alter_payment_amount_alter_payment_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
