# Generated by Django 4.2.11 on 2024-04-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keshoApp', '0004_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babe',
            old_name='time_in',
            new_name='TimeIn',
        ),
        migrations.RenameField(
            model_name='babe',
            old_name='time_out',
            new_name='TimeOut',
        ),
        migrations.RemoveField(
            model_name='babe',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='babe',
            name='Name_of_person_who_brought_the_baby',
        ),
        migrations.RemoveField(
            model_name='babe',
            name='c_fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_number',
        ),
        migrations.AddField(
            model_name='babe',
            name='NameOfPersonBringingBabe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keshoApp.babe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='Shs.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='babe',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
