# Generated by Django 4.2.11 on 2024-04-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keshoApp', '0005_rename_time_in_babe_timein_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paye',
            new_name='payee',
        ),
    ]
